apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-configs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
      requests:
        storage: 500Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
      requests:
        storage: 30Ti
  storageClassName: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rr-env
  namespace: default
data:
  TZ: "America/Louisville"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: sctx/overseerr:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /app/config
        ports:
        - containerPort: 5055
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: default
spec:
  selector:
    app: overseerr
  ports:
  - protocol: TCP
    port: 5055
    targetPort: 5055
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: overseerr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              number: 5055
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:develop
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /app/config
        ports:
        - containerPort: 9696
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
spec:
  selector:
    app: prowlarr
  ports:
  - protocol: TCP
    port: 9696
    targetPort: 9696
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: prowlarr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: lscr.io/linuxserver/sonarr:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - containerPort: 8989
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: data
        persistentVolumeClaim:
          claimName: k3s-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: default
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: sonarr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - containerPort: 8989
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: data
        persistentVolumeClaim:
          claimName: k3s-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: default
spec:
  selector:
    app: radarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: radarr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - containerPort: 8989
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: data
        persistentVolumeClaim:
          claimName: k3s-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: default
spec:
  selector:
    app: lidarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: lidarr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lidarr
            port:
              number: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      containers:
      - name: bazarr
        image: lscr.io/linuxserver/bazarr:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        ports:
        - containerPort: 6767
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: data
        persistentVolumeClaim:
          claimName: k3s-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: default
spec:
  selector:
    app: bazarr
  ports:
  - protocol: TCP
    port: 6767
    targetPort: 6767
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: bazarr.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s1
                - k3s2
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
        - name: transcode
          mountPath: /transcode
        - name: dri
          mountPath: /dev/dri
        ports:
        - containerPort: 32400
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: media
        persistentVolumeClaim:
          claimName: k3s-data-pvc
      - name: transcode
        hostPath:
          path: /mnt/transcode
          type: Directory
      - name: dri
        hostPath:
          path: /dev/dri
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  selector:
    app: plex
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: plex.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plex
            port:
              number: 32400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd:latest
        envFrom:
        - configMapRef:
            name: rr-env
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /data/usenet
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: k3s-configs-pvc
      - name: downloads
        hostPath:
          path: /mnt/scratch
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: default
spec:
  selector:
    app: sabnzbd
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: cilium
spec:
  rules:
  - host: sabnzbd.fletcherlabs.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sabnzbd
            port:
              number: 8080
